# URLDB插件配置文件
# 请根据你的实际API服务修改以下配置

# API域名配置
api_domain: "https://pan.l9.lc"

# API端点路径
api_endpoint: "/api/public/resources/search"

# API密钥（如果需要的话）
api_token: ""

# 其他可选配置
# 请求超时时间（秒）
timeout: 30

# 最大返回结果数量
max_results: 5 