# URLDB插件配置文件
# 请根据你的实际API服务修改以下配置

# API域名配置
api_domain: "https://api.example.com"

# API端点路径
api_endpoint: "/search"

# API密钥（如果需要的话）
api_key: ""

# 其他可选配置
# 请求超时时间（秒）
timeout: 30

# 最大返回结果数量
max_results: 5 